
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://yazzledazzle.github.io/yazzledazzle.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /yazzledazzle.github.io

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Yhana Lucas"
title: "~ Yhana Lucas ~"
description: "Blog and website of Yhana Lucas. Opinions expressed are mine."
keywords: "yhana, lucas, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/heading-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 5
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "“We have to continually be jumping off cliffs and developing our wings on the way down.” ― Kurt Vonnegut"
  - text: "“Of all the words of mice and men, the saddest are, ”It might have been”.” ― Kurt Vonnegut"
  - text: "“The universe is a big place, perhaps the biggest.” ― Kurt Vonnegut"
  - text: "“We are an impossibility in an impossible universe.” ― Ray Bradbury"
  - text: "“Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.” ― Marie Curie"
  - text: "“You cannot teach a man anything; you can only help him discover it in himself.” - Galileo"

me-img: "/img/yhana-display-pic.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/lyn-pic.jpg"
    date: "May 2016"
    description: "Networking event"
  - image: "/img/timeline/veritasium-pic.jpg"
    date: "March 2016"
    description: "Met everyones favorite Youtuber"

# First image of the Timeline

timeline-img: "/img/timeline/default.jpg"

###########
# Contact #
###########

email: "yhana.lucas@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Yhana has close to 2 years' experience in the Research & Development and Government Incentives sector, supporting leading Australian innovators through her positions at two major firms."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/getoffdomaths"
  - title: "twitter"
    url: "https://twitter.com/yeanahsofia"
  - title: "github"
    url: "https://github.com/yazzledazzle"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
